version: '3.3'

networks:
  searxng-go:
    driver: bridge

services:
  api:
    build: .
    ports:
      - 8888:8888
    container_name: searxng-go-api
    networks:
      - searxng-go
    command: ["api"]
  web:
    build: .
    ports:
      - 3000:3000
    container_name: searxng-go-web
    networks:
      - searxng-go
    command: ["web"]
    depends_on:
      - api