version: '3.3'

networks:
  searxng-go:
    driver: bridge

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 9999:9999
    container_name: searxng-go-api
    networks:
      - searxng-go
    command: ["api", "-a", ":9999"]
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - 3000:3000
    container_name: searxng-go-web
    networks:
      - searxng-go
    command: ["web"]
    depends_on:
      - api